[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
handlebars = "4.0"

serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0"

pulldown-cmark = "0.8.0"